# Generated by Django 5.2.15 on 2026-06-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('INVALID_RFID', 'Invalid RFID'), ('FINGERPRINT_FAILED', 'Fingerprint Failed'), ('FACE_NOT_MATCHED', 'Face Not Matched'), ('DOOR_FORCED', 'Door Forced Open'), ('TAILGATING', 'Tailgating')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
