# Generated by Django 5.2.15 on 2026-07-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('INVALID_RFID', 'Invalid RFID'), ('FINGERPRINT_FAILED', 'Fingerprint Failed'), ('FACE_NOT_MATCHED', 'Face Not Matched'), ('DOOR_FORCED', 'Door Forced Open'), ('TAILGATING', 'Tailgating'), ('MULTIPLE_SCAN', 'Multiple Scan After Checkout'), ('SENSOR_THRESHOLD', 'Ambient Sensor Threshold Exceeded')], max_length=50),
        ),
    ]
