# Generated by Django 5.2.15 on 2026-06-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('RFID', 'RFID'), ('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition'), ('DOOR', 'Door Sensor'), ('EXIT', 'Exit Sensor')], max_length=20)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('ACCESS_GRANTED', 'Access Granted'), ('ACCESS_DENIED', 'Access Denied')], max_length=20)),
                ('device_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_events', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Sensor Event',
                'verbose_name_plural': 'Sensor Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
