# Generated by Django 5.2.15 on 2026-07-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorevent',
            name='fog_node_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensorevent',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorevent',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensorevent',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_events', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='event_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('ACCESS_GRANTED', 'Access Granted'), ('ACCESS_DENIED', 'Access Denied'), ('RFID_SCAN', 'RFID Scan'), ('INVALID_RFID', 'Invalid RFID'), ('DOOR_OPEN', 'Door Open'), ('DOOR_CLOSED', 'Door Closed'), ('ENTRY_DETECTED', 'Entry Detected'), ('EXIT_DETECTED', 'Exit Detected'), ('READING', 'Ambient Reading'), ('THRESHOLD_EXCEEDED', 'Threshold Exceeded'), ('FACE_VERIFIED', 'Face Verified')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='sensor_type',
            field=models.CharField(choices=[('RFID', 'RFID'), ('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition'), ('DOOR', 'Door Sensor'), ('EXIT', 'Exit Sensor'), ('TEMPERATURE', 'Temperature Sensor'), ('HUMIDITY', 'Humidity Sensor'), ('OCCUPANCY', 'Occupancy / Motion Sensor'), ('CAMERA', 'Camera / Face Verification')], max_length=20),
        ),
    ]
