# Generated by Django 5.2.15 on 2026-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('Admin', 'Administration'), ('Security', 'Security')], max_length=20)),
                ('rfid_tag', models.CharField(max_length=50, unique=True)),
                ('fingerprint_id', models.CharField(blank=True, max_length=100, null=True)),
                ('face_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
    ]
